server:
  port: 8090

spring:
  application:
    name: image-historique
  
  datasource:
    # On pointe vers l'adresse de MySQL dans XAMPP
    url: jdbc:mysql://localhost:3306/image_historique_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:     # Par défaut dans XAMPP, le mot de passe est vide
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Crée les tables automatiquement à partir de vos entités Java
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka